### ISSUE TITLE
Create usage instruction in Readme

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/sotory#2]
We don't provide yet on how to use this library on your project. Although there are `demo` directory, I think having clear usage instruction in `README.md` is the best choice.

Basically to use this library, all you need is to create configuration object configuration like this:

```ts
interface IConfig {
  storyLength: number // length of each story, in milisecond
  endpoint: string // the source of your story data
  avatar: string // the avatar that displaying your story
  identifier?: string // not used yet, maybe we need to remote it?
  target: string // target dom element to display the avatar. Should be `id`.
}
```

example:

```ts
const config: IConfig = {
  storyLength: 5000,
  endpoint: 'https://jsonbox.io/box_54808b72dbcf8f9b24f7',
  avatar: 'https://avatars0.githubusercontent.com/u/43804217?v=4',
  identifier: 'evilfactorylabs',
  target: '#js-sotory'
}
```

After that we need to instantiate the object (with `config` as a parameter) and call the `init` method from it.

```ts
const sotory = new Sotory(config)

sotory.init()
```

That's it! You can use your own instruction style by following above style.

**Comment by kevanantha** [comment]
Working on it

**Comment by r17x** [comment]
Close, Resolve https://github.com/evilfactorylabs/sotory/pull/3
